"""Initial migration after reset

Revision ID: 0a6d8685798d
Revises: a07ac48e9046
Create Date: 2025-08-01 00:23:38.120149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6d8685798d'
down_revision = 'a07ac48e9046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_general_transporte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_individual_transporte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_general_guias', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_individual_guias', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_general_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_individual_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ganancia_pp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ganancia_gral', sa.Float(), nullable=True))
        batch_op.alter_column('total_individual_personales',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.alter_column('total_individual_personales',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('ganancia_gral')
        batch_op.drop_column('ganancia_pp')
        batch_op.drop_column('total_individual_total')
        batch_op.drop_column('total_general_total')
        batch_op.drop_column('total_individual_guias')
        batch_op.drop_column('total_general_guias')
        batch_op.drop_column('total_individual_transporte')
        batch_op.drop_column('total_general_transporte')

    # ### end Alembic commands ###
