"""Initial migration after reset

Revision ID: a07ac48e9046
Revises: 9406e91b75ac
Create Date: 2025-07-31 23:51:08.414782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07ac48e9046'
down_revision = '9406e91b75ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_individual_personales', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_column('total_individual_personales')

    # ### end Alembic commands ###
